"""
r1_05_figures.py — Figures for the revised submission.

  * Figures 2, 3, S2, S3: unchanged (do not depend on HHI or Tyrving) -> copied.
  * Figure 1 (conceptual model): SDT box replaced by Kretchmar (cited in the text).
  * Figure S0 (flow diagram): complete-case n and missingness text updated.
  * Figure S1 (post-baseline Cox calibration): regenerated by the R1 re-run (r1_02).
  * Figure S4 (time-varying hazard ratios): now drawn from the re-run table
    (tableS8_time_varying.csv) instead of hard-coded values.
  * Figure S5 (within-athlete event study): new, produced by r1_03.
"""

import shutil
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402
from matplotlib.patches import FancyBboxPatch  # noqa: E402

HERE = Path(__file__).parent
R1 = HERE.parent
FIG = R1 / "figures"
SUB_FIG = Path("/Users/atleguttormsen/Dropbox/Aktuelt1/Florida25/Statistikk/forskning/ncc-kohort/submission_pse/figures")
RERUN = R1 / "tables" / "rerun"


def conceptual_model():
    """Figure 1, as submitted except: the SDT box (a framework not used or cited in the text)
    is replaced by Kretchmar's meaning-in-movement account (cited in Section 1.1), and the
    centre box is labelled a behavioral marker of (not a measure of) disengagement."""
    fig, ax = plt.subplots(figsize=(8, 4.5))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 6)
    ax.axis("off")
    ax.text(5, 5.7, "A behavioral-marker model of youth-sport disengagement", fontsize=11, fontweight="bold", ha="center")

    def box(x, y, w, h, text, color, fontsize=9, fc="white"):
        ax.add_patch(FancyBboxPatch((x - w / 2, y - h / 2), w, h, boxstyle="round,pad=0.05", linewidth=1.4,
                                    edgecolor=color, facecolor=fc, alpha=0.95))
        ax.text(x, y, text, ha="center", va="center", fontsize=fontsize)

    ax.text(1.5, 4.85, "Theoretical mechanisms\n(not directly observed)", fontsize=8.5, ha="center", style="italic", color="#555555")
    box(1.5, 4.0, 2.5, 0.55, "Engagement balance\n(Scanlan SCM)", "#1976D2", 8.5)
    box(1.5, 3.2, 2.5, 0.55, "Meaning in movement\n(Kretchmar)", "#1976D2", 8.5)
    box(1.5, 2.4, 2.5, 0.55, "Role-exit deliberation\n(Ebaugh; Eliasson)", "#1976D2", 8.5)
    ax.text(5, 4.85, "Observable behavioral marker\n(this study)", fontsize=8.5, ha="center", style="italic", color="#555555")
    box(5, 3.2, 2.5, 1.5, "Annual competition\nvolume\n\n(meets per year,\nages 13–18)", "#2E7D32", 9.5, fc="#E8F5E9")
    ax.text(8.5, 4.85, "Outcome\n(this study)", fontsize=8.5, ha="center", style="italic", color="#555555")
    box(8.5, 3.2, 2.5, 1.5, "Active senior\nretention\n\n(≥ 2 results in\nany year, age ≥ 20)", "#C62828", 9.5, fc="#FFEBEE")
    ax.annotate("", xy=(3.7, 3.2), xytext=(2.85, 3.2), arrowprops=dict(arrowstyle="->", color="#888", lw=1.4))
    ax.annotate("", xy=(7.15, 3.2), xytext=(6.3, 3.2), arrowprops=dict(arrowstyle="->", color="#888", lw=1.4))
    ax.text(3.3, 3.4, "produces\nfootprint in", fontsize=7.5, ha="center", color="#555")
    ax.text(6.75, 3.4, "precedes", fontsize=7.5, ha="center", color="#555")
    ax.text(5, 0.85, "Prediction: future retainers and future dropouts should differ in measurable competition behavior\n"
            "before formal exit, with divergence intensifying at qualification-milestone years (age 15–16).",
            fontsize=8.5, ha="center", style="italic",
            bbox=dict(boxstyle="round,pad=0.4", facecolor="#FAFAFA", edgecolor="#BDBDBD"))
    fig.tight_layout()
    fig.savefig(FIG / "fig1_conceptual_model.png", dpi=300, bbox_inches="tight")
    plt.close(fig)


def copy_unchanged():
    for f in ["fig2_volume_trajectory.png", "fig3_km_vol_quintile.png",
              "figS2_km_overall_sex.png", "figS3_km_msk_typer.png"]:
        shutil.copy(SUB_FIG / f, FIG / f)
    shutil.copy(R1 / "_rerun" / "submission_pse" / "figures" / "figS1_calibration.png", FIG / "figS1_calibration.png")


def flow_diagram(n_cc, n_tyr_missing, n_sex_unknown):
    fig, ax = plt.subplots(figsize=(10, 9.5))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)
    ax.axis("off")

    def box(x, y, w, h, text, color, fc="white", fontsize=9):
        ax.add_patch(FancyBboxPatch((x - w / 2, y - h / 2), w, h, boxstyle="round,pad=0.05",
                                    linewidth=1.4, edgecolor=color, facecolor=fc))
        ax.text(x, y, text, ha="center", va="center", fontsize=fontsize)

    def arrow(x1, y1, x2, y2):
        ax.annotate("", xy=(x2, y2), xytext=(x1, y1), arrowprops=dict(arrowstyle="->", color="#424242", lw=1.2))

    box(3, 9.3, 5.5, 0.7, "Athletes at six autumn editions of the regional 13–14 meet (2011–2016)\n"
        "three venues: eastern, western, mid Norway", "#1565C0", "#E3F2FD")
    arrow(3, 8.9, 3, 8.35)
    box(3, 8.0, 5.5, 0.6, "Restrict birth years to 1998–2002\n(1997 and 2003 had only one eligible edition)",
        "#1565C0", "#E3F2FD")
    arrow(3, 7.65, 3, 7.1)
    box(3, 6.75, 5.5, 0.6, "De-duplicate athletes in both a 13- and a 14-year-old edition\n(earlier edition = baseline)",
        "#1565C0", "#E3F2FD")
    arrow(3, 6.4, 3, 5.85)
    box(3, 5.5, 5.5, 0.6, "Total cohort: N = 2,123 (996 male, 1,103 female, 24 sex not registered)",
        "#2E7D32", "#E8F5E9", fontsize=9.5)
    arrow(2.0, 5.15, 1.6, 4.65)
    arrow(4.0, 5.15, 4.4, 4.65)
    box(1.6, 4.3, 2.6, 0.6, "Cohort A (1998–2000)\nn = 1,301", "#2E7D32", "#E8F5E9", fontsize=8.5)
    box(4.4, 4.3, 2.6, 0.6, "Cohort B (2001–2002)\nn = 822", "#2E7D32", "#E8F5E9", fontsize=8.5)
    box(3, 3.25, 5.5, 0.6, "Predictors observed at ages 13–14 only (primary analysis)", "#6A1B9A", "#F3E5F5", fontsize=8.5)
    arrow(3, 3.95, 3, 3.6)
    box(3, 2.0, 5.5, 0.7, "Outcome window: ages 20+\nPrimary: ≥2 results in any senior-age year "
        "(n_retainers = 348, 16.4%)", "#C62828", "#FFEBEE", fontsize=8.5)
    arrow(3, 2.9, 3, 2.4)
    box(8.0, 3.6, 3.5, 0.7, "Maximum follow-up:\n14 years (Cohort A)\n9 years (Cohort B)", "#757575", "#FAFAFA", fontsize=8.5)
    box(3, 0.6, 5.5, 0.75, f"Complete-case analysis: n = {n_cc:,}\n(excluded: {n_sex_unknown} without registered sex; "
        f"{n_tyr_missing} further\nwithout a baseline Tyrving score)", "#757575", "#FAFAFA", fontsize=8.5)
    arrow(3, 1.6, 3, 1.0)
    fig.tight_layout()
    fig.savefig(FIG / "figS0_flow_diagram.png", dpi=300, bbox_inches="tight")
    plt.close(fig)


def forest_time_varying():
    t = pd.read_csv(RERUN / "tableS8_time_varying.csv")
    names = {"vol_milepael_z": "Volume at ages 15–16 (per SD)", "n_msk_typer": "Championship types (per type)",
             "tyrving_best_z": "Tyrving (per SD)", "hhi_early_z": "HHI, ages 13–14 (per SD)", "female": "Female"}
    periods = list(dict.fromkeys(t["Period"]))
    labels = {p: p.replace("-", "–").replace("age ", "ages ") for p in periods}
    colors = dict(zip(periods, ["#2a78d6", "#eb6834", "#898781"]))
    offset = dict(zip(periods, [0.22, 0.0, -0.22]))
    covs = list(names)
    fig, ax = plt.subplots(figsize=(7.8, 5.2))
    for i, c in enumerate(covs):
        for p in periods:
            r = t[(t["Covariate"] == c) & (t["Period"] == p)].iloc[0]
            y = len(covs) - i + offset[p]
            ax.plot([r["CI low"], r["CI high"]], [y, y], color=colors[p], lw=1.6)
            ax.plot(r["HR"], y, "o", color=colors[p], ms=6.5)
    ax.axvline(1.0, color="#52514e", ls="--", lw=0.9)
    ax.set_yticks(range(1, len(covs) + 1))
    ax.set_yticklabels([names[c] for c in covs][::-1])
    ax.set_xscale("log")
    ax.set_xticks([0.1, 0.2, 0.5, 1.0, 2.0])
    ax.set_xticklabels(["0.1", "0.2", "0.5", "1.0", "2.0"])
    ax.set_xlim(0.08, 2.2)
    ax.set_xlabel("Hazard ratio (log scale)")
    ax.grid(axis="x", alpha=0.25)
    ax.spines[["top", "right"]].set_visible(False)
    handles = [plt.Line2D([0], [0], marker="o", color=colors[p], lw=1.6, ms=6.5, label=labels[p]) for p in periods]
    ax.legend(handles=handles, loc="upper left", bbox_to_anchor=(1.02, 1.0), fontsize=8.5, title="Follow-up window",
              title_fontsize=8.5, frameon=False)
    fig.tight_layout()
    fig.savefig(FIG / "figS4_time_varying_forest.png", dpi=300, bbox_inches="tight")
    plt.close(fig)


def main():
    copy_unchanged()
    conceptual_model()
    flow_diagram(n_cc=2095, n_tyr_missing=4, n_sex_unknown=24)
    forest_time_varying()
    print(sorted(p.name for p in FIG.glob("*.png")))


if __name__ == "__main__":
    main()
